// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    NavItem: typeof import('./src/components/NavBar/NavItem.vue')['default']
    NewsItem0: typeof import('./src/components/NewsList/NewsItem/NewsItem0.vue')['default']
    NewsItem1: typeof import('./src/components/NewsList/NewsItem/NewsItem1.vue')['default']
    NewsItem2: typeof import('./src/components/NewsList/NewsItem/NewsItem2.vue')['default']
    NewsItem3: typeof import('./src/components/NewsList/NewsItem/NewsItem3.vue')['default']
    NewsList: typeof import('./src/components/NewsList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
